config/routes.rb
AlertiTest::Application.routes.draw do

  namespace :admin do
    resources :articles, :only => [:show] do
      resources :stats_article_comments, :only => [:index]
    end
    resources :comments, :only => [:update, :destroy]
  end

  resources :articles, :except => [:update, :edit] do
    resources :comments, :only => [:create]
  end
  root :to => 'articles#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :article_id,
  :content,
  :is_moderated,
  :opinion,
  :user_id

  belongs_to :article

  validates :content, :presence => true
  validates :article_id, :presence => true

	scope :moderated, where("is_moderated = ?", true)
	scope :recent, order("created_at DESC")
	scope :neutral, where("opinion = ?", "neutral" )
	scope :positive, where("opinion = ?", "positive" )
	scope :negative, where("opinion = ?", "negative" )
	scope :from_article, lambda { |article_id|
    if article_id
      where(:article_id => article_id)
    else
      []
    end
  }


  def self.search(article_id, from, to, status)
    comments = Comment.from_article(article_id).recent

    begin
      unless from.empty?
        from_date = DateTime.parse(from)
        comments = comments.where("created_at >= ?", from_date)
      end
    rescue
      puts "From date incorrect #{from.to_s}"
      raise "from date format incorrect #{from.to_s}"
    end
    begin
      unless to.empty?
        to_date = DateTime.parse(to)
        comments = comments.where("created_at <= ?", to_date)
      end
    rescue
      puts "To date incorrect #{to.to_s}"
      raise "to date format incorrect #{to.to_s}"
    end
    case status
      when "mod"
        comments = comments.where(:is_moderated => true)
      when "not_mod"
        comments = comments.where(:is_moderated => false)
      when "neg"
        comments = comments.where(:opinion => "negative")
      when "pos"
        comments = comments.where(:opinion => "positive")
      when "neutr"
        comments = comments.where(:opinion => "neutral")
    end

    return comments
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  cache_sweeper :comment_sweeper
  # GET /comments
  # GET /comments.json
  # def index
  #   @comments = Comment.all

  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @comments }
  #   end
  # end



  # def edit
  #   @comment = Comment.find(params[:id])
  # end



  def update
    @comment = Comment.find(params[:id])
    opinion = params[:comment][:opinion]
    result = @comment.update_attributes(:opinion => opinion, :is_moderated => (opinion != ""))
    respond_to do |format|
      if result
        format.html { redirect_to [:admin, @comment.article], notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @article = @comment.article
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to [:admin, @article], notice: 'Comment was successfully Destroyed.' }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  cache_sweeper :comment_sweeper

  def create
    id = params[:comment][:article_id]

    @article = Rails.cache.fetch("article/#{id}") do
      Article.find(id)
    end

    @comment = @article.comments.build(params[:comment])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to(@article, :notice => 'Comment was successfully created. Waiting for moderation...') }
      else
        format.html { redirect_to(@article, :notice =>
        'Comment could not be saved. Please fill in all fields')}

      end
    end
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/_article_comments.html.erb
<div class="pull-right">
	<%= link_to "Stats", admin_article_stats_article_comments_path(@article.id), :class => "btn btn-primary"  %>
</div>
<p>Total: <%= @count %></p>
<br>
<% cache ["v1", cache_key_for(@comments, @count), params[:id], params[:page], params[:from], params[:to], @status] do %>
	<table class="table table-striped">
		<tr>
			<th>Id</th>
			<th>User</th>
			<th>Creation Date</th>
			<th>Content</th>
			<th>Moderated</th>
			<th>Opinion</th>
			<th></th>
			<th></th>
		</tr>
		<% @comments.each do |comment| %>
		<tr>
			<td><%= comment.id %></td>
			<td>user_<%= comment.user_id %></td>
			<td><%= comment.created_at %></td>
			<td><%= comment.content %></td>
			<td><%= render :partial => "comments/moderated", :locals => {:moderated => comment.is_moderated}  %></td>
			<td><%= render :partial => "comments/opinion", :locals => {:opinion => comment.opinion}  %></td>

			<td>
				<select class="input-small opinion_select" data-comment-id="<%= comment.id %>">
					<option value="" <% if !comment.is_moderated %>selected="selected"<% end %> >Not moderated</option>
					<option value="positive" <% if comment.opinion == "positive" %>selected="selected"<% end %> >Positive</option>
					<option value="negative" <% if comment.opinion == "negative"%>selected="selected"<% end %> >Negative</option>
					<option value="neutral" <% if comment.opinion == "neutral" %>selected="selected"<% end %> >Neutral</option>
				</select>
			</td>
			<td>
			<%= link_to 'Destroy', [:admin, comment], method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
		</tr>
		<% end %>
	</table>
<% end %>

<% unless @comments.empty? %>
<%= will_paginate @comments %>
<% end %>

app/views/admin/comments/_search_bar.html.erb
<div class="well">
	<h3>Filters</h3>

	<%= form_tag admin_article_path(@article), :method=>"get" do %>
		<div class="control-group">
			<label class="control-label">From:</label>
			<div class="controls">
				<div class="input-append date " id="from" data-date="<%= Date.today.to_s %>" data-date-format="yyyy-mm-dd">
					<%= text_field_tag :from, params[:from], {:class=> "span2"} %>
					<span class="add-on"><i class="icon-th"></i></span>
				</div>
			</div>
		</div>

		<div class="control-group">
			<label class="control-label">To:</label>
			<div class="controls">
				<div class="input-append date " id="to" data-date="<%= Date.today.to_s %>" data-date-format="yyyy-mm-dd">
					<%= text_field_tag :to, params[:to], {:class=> "span2"}  %>
					<span class="add-on"><i class="icon-th"></i></span>
				</div>
			</div>
		</div>

		<div class="control-group">
			<label class="control-label" for="inputEmail">Filter</label>
			<div class="controls">
				<%= select "comment", "status", [["All", ""], ["Moderated", "mod"], ["Not moderated", "not_mod"], ["Positive", "pos"], ["Negative","neg"], ["Neutral","neutr"]], :selected => @status %>
			</div>
		</div>
		<div class="control-group">
			<div class="controls">
				 <%= submit_tag "Search", :class => "btn btn-primary" %>
			</div>
		</div>
	<% end %>

</div>