config/routes.rb
AlertiTest::Application.routes.draw do

  namespace :admin do
    resources :articles, :only => [:show] do
      resources :stats_article_comments, :only => [:index]
    end
    resources :comments, :only => [:update, :destroy]
  end

  resources :articles, :except => [:update, :edit] do
    resources :comments, :only => [:create]
  end
  root :to => 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :title, :user_id

  has_many :comments
  has_many :stats_article_comments

	scope :recent, order("created_at DESC")
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController

  def show
    id = params[:id]
    flash[:notice] = nil
    @status = (params[:comment]) ? params[:comment][:status] : ""
    @article = Rails.cache.fetch("article/#{id}") do
      Article.find(id)
    end
      # default to all comments
    if params[:commit] != "Search"
      @comments = Comment.from_article(id)
        .recent
        .paginate(:page => params[:page], :per_page => 10)
    else
      begin
        @comments = Comment.search(id, params[:from], params[:to], @status)
        .paginate(:page => params[:page], :per_page => 10)

      rescue
        flash[:notice] = "Date format incorrect in search form, YYYY-MM-DD format expected."
        @comments = []
      end
    end

    @count = @comments.count

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  cache_sweeper :article_sweeper
  # GET /articles
  # GET /articles.json
  def index
    # @articles = Article.select([:id, :title]).recent.limit(10).all
    @articles = Rails.cache.fetch("articles/last_10") do
      Article.select([:id, :title]).recent.limit(10).all
    end

    # @count = Article.count
    @count = Rails.cache.fetch("articles/count") do
      Article.count
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    id = params[:id]
    @article = Rails.cache.fetch("article/#{id}") do
      Article.find(id)
    end

    @comments = Rails.cache.fetch("article/#{id}/comments/moderated/true/last_20") do
      Comment.from_article(id).recent.moderated.limit(20).all
    end

    @countComments = Rails.cache.fetch("article/#{id}/comments/moderated/true/count") do
      Comment.from_article(id).moderated.count
    end


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # # GET /articles/1/edit
  # def edit
  #   @article = Article.find(params[:id])
  # end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    id = params[:id]
    @article = Rails.cache.fetch("article/#{id}") do
      Article.find(id)
    end
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper

end

app/views/articles/_form.html.erb
<%= form_for(@article, :class=> "form-horizontal") do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="control-group">
  <label class="control-label">Title:</label>
  <div class="controls">
    <%= f.text_field :title%>
  </div>
</div>

<div class="control-group">
  <label class="control-label">Content:</label>
  <div class="controls">
    <%= f.text_area :content, :rows => 5, :cols => 20 %>
  </div>
</div>

<div class="control-group">
  <label class="control-label">User id:</label>
  <div class="controls">
    <%= f.text_field :user_id%>
  </div>
</div>


<div class="control-group">
  <%= f.submit "Create Article", :class => "btn btn-primary"  %>
  <%= link_to 'Cancel', articles_path, :class => "btn" %>

</div>


<% end %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<p>Total: <%= @count %></p>
<p><%= link_to 'New Article', new_article_path , :class => "btn btn-primary" %></p>
<div class="row">
<table class="table table-striped span6">
  <tr>
    <th>Id</th>
    <th>Title</th>
    <!-- <th>Content</th> -->
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
    <tr>
      <td><%= article.id %></td>
      <td><%= article.title %></td>
      <td><%= link_to 'Show', article, :class => "btn btn-primary"  %></td>
      <td><%= link_to 'Admin', admin_article_path(article), :class => "btn"  %></td>
      <td><%= link_to 'Destroy', article, method: :delete, :class => "btn btn-danger" %></td>
    </tr>
<% end %>
</table>

<br />


</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<% cache [ "show_article", @article ] do %>
	<div class="pull-right">
		<%= link_to 'Admin', admin_article_path(@article), :class => "btn btn-primary"  %>
	</div>
	<h1>
	  <%= @article.title %>
	</h1>

	<p>
	  <%= @article.content %>
	</p>
<% end %>

<hr>
<h2>Comments</h2>
<%= render :partial => "comments/form_article_comment" %>
<hr>

<%= render :partial => "comments/article_comments" %>